name: Docker Image CI

#on:
#  workflow_dispatch: # Allows manual triggering via API or UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-actions:new
    
    - name: Run the Docker Image
      run:  sudo docker run my-actions:new

  container:
    runs-on: ubuntu-latest
    needs: docker-build
    container: node:10.16-jessie
    steps:
      - run: |
          hostname && pwd && ip addr
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container    
      
